    platform :ios, '8.0'
target 'Journal’ do
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'Reachability', '~> 3.2'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'Toast', '~> 3.1.0'
    pod 'IQKeyboardManager'
    pod 'YYModel'
end
